# Change these first
owner: vvphuc # Your GitHub organization or username, where this repository lives
repo: uptimestatus # The name of this repository

sites:
  - name: Panel of Dau-gia
    url: https://panel.phanmem.work
  - name: Dau-gia.com
    url: http://dau-gia.com
  - name: intecks.com
    url: https://intecks.com
  - name: apcaustralia.net.au
    url: https://apcaustralia.net.au
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.intecks.com
  baseUrl: /uptimestatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Website Up Time
  introTitle: "**Upptime** checks status of page & monitor."
  introMessage: "**real-time** data"
  navbar:
    - title: Status
      href: /uptimestatus
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
